{
	"users": [
	  { 
		"id": 1,
		"avatar":"../img",
		"username": "lorem",
		"email": "loremipsum@gmail.com",
		"password": "1",
		"property_id": 1,
		"role":"admin"
	  },
	  { 
		"id": 2,
		"avatar":"../img",
		"username": "lorem",
		"email": "loremipsum@gmail.com",
		"password": "2",
		"property_id": 2,
		"role":"admin"
	  },
	  { 
		"id": 3,
		"avatar":"../img",
		"username": "lorem",
		"email": "loremipsum@gmail.com",
		"password": "3",
		"property_id": 3,
		"role":"admin"
	  }
	],
	"auth":[
	  {
		"id":1
	  }
	],     
	"homes": [
	  {
		"id":1,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0
	  },
	  {
		"id":2,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0
	  },
	  {
		"id":3,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0         
	  },
	  {
		"id":4,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0         
	  },
	  {
		"id":5,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0
	  },
	  {
		"id":6,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0            
	  },
	  {
		"id":7,
		"kind":"",
		"name":"some desc",
		"photos":{"list of photos":"",""},
		"description":"some desc long",
		"location":"41.3743,2.1759",
		"user_id":"1",
		"bedroom":"3 or more",
		"bathrooms":"2",
		"kitchen":"fully fitted",
		"condition":"new",
		"price":1200,
		"lift":0,
		"pets_allowed":1,
		"garden":0,
		"swimming_pool":0,
		"air-conditioning":1,
		"heating":0,
		"floor":"3rd floor",
		"orientation":"N",
		"energy_certificate":"very good",
		"parking":"yes",
		"timestamp_created":12345535643,
		"timestamp_updated":132445647678,
		"bargain":0,
		"terrace":0 
	  }],
	  "offices":[
		{
		  "id":1,
		  "name":"some desc",
		  "photos":{"list of photos":"",""},
		  "description":"some desc long",
		  "location":"41.3743,2.1759",
		  "user_id":"1",
		  "kind":"private",
		  "price":12000,
		  "lift":0,
		  "terrace":0,
		  "pets_allowed":1,
		  "air-conditioning":1,
		  "floor":"3rd floor",
		  "orientation":"N",
		  "energy_certificate":"very good",
		  "parking":"yes",
		  "timestamp_created":12345535643,
		  "timestamp_updated":132445647678,
		  "bargain":0
		},
		{
		  "id":2,
		  "name":"some desc",
		  "photos":{"list of photos":"",""},
		  "description":"some desc long",
		  "location":"41.3743,2.1759",
		  "user_id":"1",
		  "kind":"private",
		  "price":12000,
		  "lift":0,
		  "terrace":0,
		  "pets_allowed":1,
		  "air-conditioning":1,
		  "floor":"3rd floor",
		  "orientation":"N",
		  "energy_certificate":"very good",
		  "parking":"yes",
		  "timestamp_created":12345535643,
		  "timestamp_updated":132445647678,
		  "bargain":0  
		},{
		  "id":3,
		  "name":"some desc",
		  "photos":{"list of photos":"",""},
		  "description":"some desc long",
		  "location":"41.3743,2.1759",
		  "user_id":"1",
		  "kind":"private",
		  "price":12000,
		  "lift":0,
		  "terrace":0,
		  "pets_allowed":1,
		  "air-conditioning":1,
		  "floor":"3rd floor",
		  "orientation":"N",
		  "energy_certificate":"very good",
		  "parking":"yes",
		  "timestamp_created":12345535643,
		  "timestamp_updated":132445647678,
		  "bargain":0
		}
	  ],
	"Buyer_requests": [
	  {
		"id":1,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":2,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":3,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":4,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":5,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":6,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  },
	  {
		"id":7,
		"property_id":1,
		"seller_id":2,
		"buyer_name":"lorem ipsum",
		"buyer_email":"lorea@abc.com",
		"buyer_message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"date_published":1234389758
	  }
  ​
	],
	"session_collection": [
	  {
		"id": 1,
		"session_cookie":"cookie",
		"expires":214087508
	  },
	  {
		"id": 2,
		"session_cookie":"cookie",
		"expires":214087508
	  },
	  {
		"id": 3,
		"session_cookie":"cookie",
		"expires":214087508
	  }
	]
  }